### Teste da API - Plataforma de Cursos

### 1. Health Check
GET http://localhost:3001/health

### 2. Cadastrar usuário
POST http://localhost:3001/usuarios
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao@email.com",
  "senha": "123456",
  "nascimento": "15/03/1995"
}

### 3. Fazer login
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "senha": "123456"
}

### 4. Listar cursos (público)
GET http://localhost:3001/cursos

### 5. Listar cursos com filtro (público)
POST http://localhost:3001/cursos
Content-Type: application/json

{
  "filtro": "JavaScript"
}

### 6. Listar cursos com status de inscrição (autenticado)
GET http://localhost:3001/cursos/inscritos
Cookie: token=SEU_TOKEN_JWT_AQUI

### 7. Inscrever em curso (autenticado)
POST http://localhost:3001/cursos/1
Cookie: token=SEU_TOKEN_JWT_AQUI

### 8. Cancelar inscrição (autenticado)
DELETE http://localhost:3001/cursos/1
Cookie: token=SEU_TOKEN_JWT_AQUI

### 9. Buscar dados do usuário logado (autenticado)
GET http://localhost:3001/me
Cookie: token=SEU_TOKEN_JWT_AQUI

### 10. Buscar dados de um usuário específico (autenticado)
GET http://localhost:3001/1
Cookie: token=SEU_TOKEN_JWT_AQUI

### 11. Listar cursos inscritos do usuário (autenticado)
GET http://localhost:3001/1/cursos
Cookie: token=SEU_TOKEN_JWT_AQUI 